#!/bin/sh
#
# @name octocopter3 SITL
#
# @type Octocopter H
#
# @maintainer KL
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MAV_TYPE 14

param set-default CA_AIRFRAME 0

param set-default CA_ROTOR_COUNT 8
param set-default CA_ROTOR0_PX 1.08     #v1.13.0 버전에서 toml 파일의 position X값
param set-default CA_ROTOR0_PY 0.543    #v1.13.0 버전에서 toml 파일의 position y값
param set-default CA_ROTOR0_KM -0.05    #v1.13.0 버전에서 toml 파일의 CM값 , -일경우 CW로 회전 
param set-default CA_ROTOR1_PX -1.08
param set-default CA_ROTOR1_PY -0.543
param set-default CA_ROTOR1_KM -0.05
param set-default CA_ROTOR2_PX 0.36
param set-default CA_ROTOR2_PY 0.543
param set-default CA_ROTOR2_KM 0.05     #v1.13.0 버전에서 toml 파일의 CM값 , +일경우 CCW로 회전
param set-default CA_ROTOR3_PX -1.08
param set-default CA_ROTOR3_PY 0.543
param set-default CA_ROTOR3_KM 0.05
param set-default CA_ROTOR4_PX 1.08
param set-default CA_ROTOR4_PY -0.543
param set-default CA_ROTOR4_KM 0.05
param set-default CA_ROTOR5_PX -0.36
param set-default CA_ROTOR5_PY -0.543
param set-default CA_ROTOR5_KM 0.05
param set-default CA_ROTOR6_PX 0.36
param set-default CA_ROTOR6_PY -0.543
param set-default CA_ROTOR6_KM -0.05
param set-default CA_ROTOR7_PX -0.36
param set-default CA_ROTOR7_PY 0.543
param set-default CA_ROTOR7_KM -0.05

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 106
param set-default PWM_MAIN_FUNC7 107
param set-default PWM_MAIN_FUNC8 108









